### ISSUE TITLE
Moredata 1 page instructions do not work.

### ISSUE THREAD

**Issue by kortschak** [dgraph-io/tutorial#6]
I am running dgraph via a docker image as per the instructions, and serving the tutorial locally. On the [more data 1 page](https://tour.dgraph.io/moredata/1/) the instructions to load the large dataset fails with the error below.

```
$ docker exec -it dgraph dgraphloader -r 1million.rdf.gz
Error response from daemon: No such container: dgraph
$ docker container ls
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
8a58af97efe7        dgraph/dgraph       "dgraph --bindall=..."   9 hours ago         Up 9 hours          0.0.0.0:8080->8080/tcp   unruffled_franklin
$ ls 1million.rdf.gz 
1million.rdf.gz
```

**Comment by manishrjain** [comment]
Try it with `docker exec -it dgraph/dgraph dgraphloader -r 1million.rdf.gz`

**Comment by MichaelJCompton** [comment]
Hi, looks like dgraph wasn't started with the right container name in docker.  Did you start it with?

```
docker run -it -p 8080:8080 -v ~/dgraph:/dgraph --name dgraph dgraph/dgraph dgraph --bindall=true
```

**Comment by kortschak** [comment]
I started it with the instructions shown on [intro 2](https://tour.dgraph.io/intro/2/):

```
docker run -it -p 8080:8080 dgraph/dgraph dgraph --bindall=true
```

**Comment by MichaelJCompton** [comment]
I pushed a change to the docker instructions.  Check intro/2 in your local version.

You might have done intro/2 before the change and and moredata/1 after it.

**Comment by MichaelJCompton** [comment]
@sungwoncho site isn't being reloaded automatically from github.

**Comment by kortschak** [comment]
That was unfortunate. Thanks, it works now.

(I'm going through the tutorial and making notes for fixes that are needed and questions that need to be clarified for a neophyte to make progress - please expect PRs and issues sometime soon).

**Comment by MichaelJCompton** [comment]
@kortschak Fantastic!  Yes, please file an issue for anything that's unclear or any bugs in the tour.

Also we are happy to take other comments on the slack channel or on discuss - those are linked off the front page of the tour.

**Comment by kortschak** [comment]
Cool. Yeah, there are specific questions I have, but I want to get generally comfortable with the system/query lang first.

**Comment by olgabot** [comment]
Hello! I'm having the same issue  where I used `docker-compose` to start the docker server:

<details>

```
Thu 27 Sep - 11:01  ~/code/cell-ontology   origin ☊ master ✔ ☗v2018-07-07  4☀ 
  docker-compose up -d    
Removing cell-ontology_server_1
cell-ontology_zero_1 is up-to-date
Recreating f7a712d96cd8_cell-ontology_server_1 ... 
Recreating f7a712d96cd8_cell-ontology_server_1 ... done
✘  Thu 27 Sep - 11:11  ~/code/cell-ontology   origin ☊ master ↑1 ✔ 4☀ 
  cat docker-compose.yml
version: "3.2"
services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  server:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8081:8081
      - 9081:9081
    restart: on-failure
    command: dgraph server --my=server:7080 --lru_mb=2048 --zero=zero:5080
  ratel:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8000:8000
    command: dgraph-ratel

volumes:
  dgraph:
```

</details>

But am getting a `Error: No such container: dgraph/dgraph` error when I try to load the data with `dgraphloader`

```
 Thu 27 Sep - 11:07  ~/code/cell-ontology   origin ☊ master ↑1 ✔ 4☀ 
  dgraph docker exec -it dgraph dgraphloader -r cl.rdf.gz 
Error: unknown command "docker" for "dgraph"
Run 'dgraph --help' for usage.
unknown command "docker" for "dgraph"

 ✘  Thu 27 Sep - 11:10  ~/code/cell-ontology   origin ☊ master ↑1 ✔ 4☀ 
  docker exec -it dgraph dgraph loader -r cl.rdf.gz 
Error: No such container: dgraph

 ✘  Thu 27 Sep - 11:11  ~/code/cell-ontology   origin ☊ master ↑1 ✔ 4☀ 
  docker exec -it dgraph/dgraph dgraph loader -r cl.rdf.gz
Error: No such container: dgraph/dgraph
```

Can you help me understand what may be going on?
Thank you!
Warmest,
Olga
